### ISSUE TITLE
jprod_lithdet needs update for COBALTv3

### ISSUE THREAD

**Issue by charliestock** [NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC#35]
The production of lithogenic detritus:

https://github.com/NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC/blob/e499f4caa67d9ce358b08c3ff9d87e6ba521352d/generic_tracers/generic_COBALT.F90#L9606-L9610

Needs to be adjusted for COBALTv3.  Lithogenic detritus is generating through the incidental consumption of lithogenic detritus by filter feeding copepods.  In COBALTv2, these copepods consumed large phytoplankton and diazotrophs, so the ratio of total filter feeding the the biomass of these prey items was used to set the conversion rate.

Fei Da has determined that the denominator in the old expression can also be problematic since both the large phytoplankton and diazotrophs can be very rare.

The introduction of medium phytoplankton and more flexible feeding has complicated this relationship.  Fei is currently testing a version where:

do k = 1, nk ; do j = jsc, jec ; do i = isc, iec   !{
    cobalt%jprod_lithdet(i,j,k)=( cobalt%total_filter_feeding(i,j,k)/ &
        ( phyto(LARGE)%f_n(i,j,k) + phyto(DIAZO)%f_n(i,j,k) + &
          0.8*phyto(MEDIUM)%f_n(i,j,k) + 0.3*phyto(SMALL)%f_n(i,j,k) + & 
          epsln) *cobalt%phi_lith + cobalt%k_lith ) * cobalt%f_lith(i,j,k)
    enddo; enddo ; enddo !} i,j,k

Initial results are promising and we anticipate a pull request in the coming days.

**Comment by feida6996** [comment]
Thank you for opening this issue, Charlie.

In the old expression, the production of lithogenic detritus could reach extremely high levels because of the small denominator, sometimes up to three to four orders of magnitude greater than the total inputs from the atmosphere and rivers. This also resulted in a crash in the flux, which never fully recovered to previous levels, as shown by the blue dots in the figure.

After implementing the new expression, we no longer have these abnormally high values. Instead, the flux reaches equilibrium after approximately 10 years, as illustrated by the red and yellow dots in the figure.
<img width="458" alt="Picture1" src="https://github.com/NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC/assets/127246088/92833d82-ce3e-4190-9f8a-14b8d0a022bb">

**Comment by yichengt900** [comment]
Thanks, @feida6996. The results you've shared are really encouraging. Feel free to open a PR when you feel it's ready. I can also conduct some tests on the regional side to check the results.

**Comment by yichengt900** [comment]
#41 is merged. I will close this issue for now. @charliestock please open an issue/PR to add short description/commet for this new change.
