### ISSUE TITLE
LA-TX shelf hypoxia area is over-estimated in the latest NWA12-COBALT configuration 

### ISSUE THREAD

**Issue by yichengt900** [NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC#70]
Our latest bi-weekly automated testing has shown that the [LA-TX shelf hypoxia area is over-estimated ](https://private-user-images.githubusercontent.com/143743249/337320174-5737942f-d85c-450a-a98a-8371e84b67cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNjM3ODQsIm5iZiI6MTcxODM2MzQ4NCwicGF0aCI6Ii8xNDM3NDMyNDkvMzM3MzIwMTc0LTU3Mzc5NDJmLWQ4NWMtNDUwYS1hOThhLTgzNzFlODRiNjdjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxMTExMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMTYzNzMwZmEyNzk2ODgzZmQxZWRmMDU4MzZlMjJlODhhZTU2ODY5MTQ4YTAyNTVmNDRhMzk3OGVhMzk3MTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qgjxng0rNn5ACBEAQ4lZRm_Hz8k-Q58322ZBauKDJN0)  in the new NWA12-COBALT configurations. Here are the changes affecting our baseline (MOM6-COBALT-NWA12 v1.0):

- physics updates: Including horizontal viscosity tuning and updates of OBC files;
- Missing Pointers for Benthic Fluxes in Direct Sinking of Phytoplankton P (#19) - this one means we will have more remineralization in the shallow water region; 
- added felim to diazo iron limitation (#31);
- Clean up of the light and phytoplankton growth calculations (#39);
- Fix setting of as_param and allow generic_COBALT to set as_param_COBALT (#42);
- jprod_lithdet update for COBALTv3 (#41);
- Recalibrate calcite and aragonite detritus flux (#47);
- Update ci for PR #59 Add support for a COBALT_param_doc file (#62)
- Add support for a COBALT_param_doc file (#59)
- Clean up and simplify bacterial production (#66)

To identify the root cause, I conducted over 10 sensitivity tests for the year 1993 with different combinations (see the figure below). I was able to pinpoint the main changes that caused the overestimation of the hypoxia area:
 
1. New Physics Configurations: Increased hypoxia area to 21,000 km². (green line)
2. Benthic Fluxes in Direct Sinking of Phytoplankton P (#19): Further increased the area to 24,000 km². (cyan line)
3. Combination of New Physics and Benthic Flux Fix: Resulted in an overestimated hypoxia area of ~27,000 km². (yellow line)

![hypoxic_area_from_monthly](https://github.com/NOAA-CEFI-Regional-Ocean-Modeling/ocean_BGC/assets/143743249/debc1e7c-6710-4d57-9c13-028595962816)

Our baseline configuration underestimates the hypoxia area (~16,000 km²), while the new changes (both physics and bgc) led to significant increases.

I believe with some fine-tuning, we can recover this. I just wanted to document all the changes we made so far to make tracking easier. FYI @charliestock and @andrew-c-ross.

**Comment by andrew-c-ross** [comment]
Thanks for looking into this, Yi-Cheng. Looking at my previous runs, the switch from underestimation to overestimation happened somewhere around the time that I switched from a version of COBALT from February 2024 to the CEFI branch with #47 merged, and switched from W92 to W14. My runs with the new physics but older BGC still underestimate. So, I think we can exclude physics changes and focus on BGC changes on or before #47.

**Comment by yichengt900** [comment]
@andrew-c-ross, thank you for your confirmation. Your findings align with what I observed in the sensitivity test. The physics changes in the original COBALTv3 (#11) improve the prediction of hypoxia areas (represented by the `green line` in my plot), but they still underestimate the area. In contrast, the old physics version with the benthic flux fix (`cyan line`, #19) provides an estimate that closely matches Matli et al. (2020). I also checked as_param (#42), but it only has a minor impact (`red line`, W14, vs. `magenta line`, W92). Initially, I thought #41 and #47 (Fei's re-calibration for calcite) were the main causes(not show in the plot), but it turns out that #19, the benthic flux fix for sinking phytoplankton P, is the key factor. This makes sense because the additional benthic fluxes of direct sinking phytoplankton P back to the water column consume oxygen for remineralization in the shallow water region.

**Comment by charliestock** [comment]
Thanks @yichengt900, @andrew-c-ross.  This is a very useful analysis and it looks like you've identified the core issue.   I am a bit surprised that erroneous phosphate burial made such a large difference since the oxygen usage is linked to N.  To impact the oxygen, the excess burial would have to lead to some downstream phosphate limitation which reduced downstream benthic fluxes/remineralization.  Could you share the paths to the baseline versus the cyan and I will see if I can confirm the mechanism?

In terms of tuning, it looks like the model is currently running without burial and with a 10m ramp up on the denitrification loss.  These would be good candidates for tuning.  A sensitivity where we turn on the burial with the same 10m ramp up would be a good start.  

@yichengt900, if you pull over my latest pull request with the improved commenting of the foodwebs, I can submit a new pull request with a logical for "do_organic_burial" and implement.  It would then be relatively simple to run a few sensitivities.  How long were the runs used the the figures?

Another options is the "nepheloid layer" assumption that individually sinking phytoplankton cells in waters less then twice the depth of active mixing remain suspended above the bottom rather than being remineralized.  The hypoxic zone would likely have some sensitivity to this as well though, based on the sensitivity thus far, I suspect that the burial is stronger.

**Comment by yichengt900** [comment]
Hi @charliestock, no problems at all. For those sensitivity runs, I only ran through 1993 (1 yr), so it should be relatively cheap and I should be able to conduct multiple tests.

You can find the history files for the `baseline` on Gaea:
/gpfs/f5/cefi/scratch/Yi-cheng.Teng/fre/ci/NWA12/20240607_oldinput_old_bgc/NWA12_CI_20240607_oldinput_old_bgc/ncrc5.intel22-prod/archive/history

And the one for the `erroneous phosphate burial` fix:
/gpfs/f5/cefi/scratch/Yi-cheng.Teng/fre/ci/NWA12/20240607_oldinput_old_bgc6/NWA12_CI_20240607_oldinput_old_bgc6/ncrc5.intel22-prod/archive/history

**Comment by charliestock** [comment]
Hi @yichengt900 @andrew-c-ross, I put in a pull request that adds a "scale_burial" term and turns it on.  I'd be very curious to see what happens to the hypoxic zone if we were to set "scale_burial" = 1.0 and keep z_burial at 10m.  Could we add this to the figure by using COBALT_override?  I suspect the hypoxic zone will shrink considerably and likely underestimate the hypoxic zone.  In theory, we could then scale up z_burial until we get the right size.

**Comment by yichengt900** [comment]
This issue is resolved with the new `scale_burial` and `z_burial` options. Close now.
